PROMPT group22_dbdrop;

PROMPT DROP TABLES;

DROP TRIGGER trg_check_seats_before_insert;
DROP TRIGGER trg_booking_decrease_seats;
DROP TRIGGER trg_cancel_increase_seats;


DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE FLIGHT CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE BOOKING_CONNECT_FLIGHT CASCADE CONSTRAINTS;

