
DROP TABLE BOOKING_CONNECT_FLIGHT CASCADE CONSTRAINTS;
DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE FLIGHT CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER(
Customer_ID VARCHAR(20),
Name VARCHAR(20) NOT NULL,
Nationality VARCHAR(20) NOT NULL,
Passport_no VARCHAR(8) NOT NULL,
PRIMARY KEY(Customer_ID)
);


CREATE TABLE FLIGHT(
Flight_No VARCHAR(5),
Depart DATE NOT NULL,
Arrive DATE NOT NULL,
Fare INTEGER NOT NULL,
Seat_Limit INTEGER NOT NULL,
Source VARCHAR(20) NOT NULL,
Dest VARCHAR(20) NOT NULL,
PRIMARY KEY(Flight_No),
CHECK (Arrive > Depart),
CHECK (Source != Dest),
CHECK (Seat_Limit >= 0)
);

CREATE TABLE BOOKING(
Booking_id VARCHAR(20),
Num_flight INTEGER ,
Total_fare INTEGER ,
Customer_ID VARCHAR(20),
PRIMARY KEY(Booking_id),
FOREIGN KEY(Customer_ID) REFERENCES CUSTOMER,
CHECK ( Num_flight  BETWEEN 1 AND 3 )
);

CREATE TABLE BOOKING_CONNECT_FLIGHT(
Booking_id VARCHAR(20),
Flight_No VARCHAR(5),
Connect_order INTEGER,
PRIMARY KEY (Booking_id,Flight_No),
FOREIGN KEY(Booking_id) REFERENCES BOOKING ON DELETE CASCADE,
FOREIGN KEY(Flight_No) REFERENCES FLIGHT,
CHECK (Connect_order BETWEEN 1 AND 3)
);

INSERT INTO CUSTOMER VALUES('C01','Alice','CHN','P1234567');
INSERT INTO CUSTOMER VALUES('C02','Bob','UK','P1111111');
INSERT INTO CUSTOMER VALUES('C03','Cole','US','P7654321');

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';

INSERT INTO FLIGHT VALUES ('CX100', '2026/3/15 12:00:00','2026/3/15 16:00:00',2000,3,'HK','Tokyo');
INSERT INTO FLIGHT VALUES ('CX102', '2026/3/15 10:00:00', '2026/3/15 13:00:00', 2000, 1, 'HK', 'Beijing');
INSERT INTO FLIGHT VALUES ('CX103', '2026/3/15 15:00:00', '2026/3/15 18:00:00', 1500, 3, 'Beijing', 'Tokyo');
INSERT INTO FLIGHT VALUES ('CX104', '2026/3/15 10:00:00', '2026/3/15 14:00:00', 1500, 3, 'New York', 'Beijing');
INSERT INTO FLIGHT VALUES ('CX105', '2026/3/15 4:00:00', '2026/3/15 9:00:00', 1000, 2, 'HK', 'New York');
INSERT INTO FLIGHT VALUES ('CX106', '2026/3/15 23:40:00', '2026/3/16 3:00:00', 5000, 3, 'New York', 'LA');
INSERT INTO FLIGHT VALUES ('CX107', '2026/3/15 8:00:00', '2026/3/15 11:00:00', 1500, 3, 'Beijing', 'Tokyo');


CREATE OR REPLACE TRIGGER trg_check_seats_before_insert
BEFORE INSERT ON BOOKING_CONNECT_FLIGHT
FOR EACH ROW
DECLARE
    v_remaining INTEGER;
BEGIN
    SELECT Seat_Limit INTO v_remaining 
    FROM FLIGHT
    WHERE Flight_No = :NEW.Flight_No;

    IF ( v_remaining <= 0) THEN
RAISE_APPLICATION_ERROR(-20001, 'Flight ' || :NEW.Flight_No || ' is full');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_booking_decrease_seats
AFTER INSERT ON BOOKING_CONNECT_FLIGHT
FOR EACH ROW
BEGIN
    UPDATE FLIGHT
    SET Seat_Limit = Seat_Limit - 1
    WHERE Flight_No = :NEW.Flight_No;
END;
/

CREATE OR REPLACE TRIGGER trg_cancel_increase_seats
AFTER DELETE ON BOOKING_CONNECT_FLIGHT
FOR EACH ROW
BEGIN
    UPDATE FLIGHT
    SET Seat_Limit = Seat_Limit + 1
    WHERE Flight_No = :OLD.Flight_No;
END;
/

COMMIT;




